# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4cda79563c0c63015149001e9eab277c9639268cb7b1183feee9a59031d4f6e7b178bd30d51b4c7bd754593735a98be177ab23e667960439d9293414827629e

test:
  secret_key_base: 3354f72e787e5bf8f109593f8392d0b7e24291ab964e93e145920a8f479d82d9623abbf6f713afd55d3c481dc50c9c1640e24cfc143ecd7ee7ac0aa982117262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
